fixed user model name
Refactor method call notation

Refactor error handlers to reduce duplicate code

simplify code

- put cascading delete behavior into model
- do not allow tasks without users (not handled by example UI)
- use Model#destroy method instead of Model#find followed by #destroy
- directly associate users when creating new tasks (one query less required)

Fix misnamed reference

Update bin/www to latest express version

Fixes #22

Update README.md

update dependencies

- update deprecated express usages

update migrations to match documentation

add missing return

Fix require resolve error on windows 10

After a bare install following instructions, hit this : Error: Cannot find module 'C:\code\testmodels/..configconfig.json'

package update

docs cleanup

sync before tests

Fix Express Standard bin/www (#45)

* Fix Express Standard bin/www
The bin/www file does not represent what is created by express during the setup process of the project.

* fix wrong name

Heroku (#46)

* Add Heroku generated app.json

* Easy deployment to Heroku

* npm install pg

Fix configuration for running tests (#47)

- Use cross-env to set NODE_ENV=test when invoking tests.
- Update config.json to use an in-memory sqlite database for tests.

Before this change, the tests were using the development configuration.

Add config options (#52)

add: style fixes, pure migrations (#54)

Docs update

docs formatting

Fix breaking changes introduced with Sequelize 4.0.0 (#62)

* Adapt to breaking changes in Sequelize 4.0

classMethods and instancesMethods were removed from options in Sequelize 4.0.0.

* Create task.js

* Create user.js

Fix README.md for V4 (#66)

fix: directly check for associate, fixes #68 (#76)

package: use pug (#77)

Update (#79)

* change: use bootstrap, update modules

* migration: use new migration setup

* docs: improve docs around migrations

* dont use classMethods

adding more code